### ISSUE TITLE
secrets: mount workers with experiment-specific secrets

### ISSUE THREAD

**Issue by lukasheinrich** [reanahub/reana-resources-k8s#10]
initially this could be enough 

```
kubectl create secret generic atlas-secrets --from-file=kerberos.keytab --from-file=`gridcert.crt` --from-file=`gridcert.key
```

this will enable the workers to authenticate as part of its specific experiment and access external data

in the deployments we would mount those e.g.

```
containers:
- name: ...
  volumeMonts:
  - name: experiment_secrets:
     mountPath: /exp_secrets
volumes:
- experiment_secrets
  name:
   secretName: atlas-secrets
     
```
